### ISSUE TITLE
Intermittent issues browsing albums

### ISSUE THREAD

**Issue by mcarlton00** [mcarlton00/mopidy-jellyfin#1]
On some albums, instead of letting your browse down into their contents mopidy gives out a traceback instead.

```
ERROR    JellyfinBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/site-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/Mopidy_Jellyfin-0.2.6-py2.7.egg/mopidy_jellyfin/library.py", line 39, in browse
    return self.backend.remote.get_tracks(album_id)
  File "/usr/lib/python2.7/site-packages/Mopidy_Jellyfin-0.2.6-py2.7.egg/mopidy_jellyfin/remote.py", line 223, in get_tracks
    key=lambda k: k['IndexNumber']
  File "/usr/lib/python2.7/site-packages/Mopidy_Jellyfin-0.2.6-py2.7.egg/mopidy_jellyfin/remote.py", line 223, in <lambda>
    key=lambda k: k['IndexNumber']
KeyError: u'IndexNumber'
```

**Comment by mcarlton00** [comment]
Caused by incomplete metadata when a track was missing a track number.  Fixed by adding a fallback value in 85259cac670a7d10331c06bf97e8e8df03c028c2
